addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.3.1")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.12")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.0")
addSbtPlugin("org.typelevel"             % "sbt-fs2-grpc"        % "2.4.7")
addSbtPlugin("com.thesamet"              % "sbt-protoc"          % "1.0.4")
